# Generated by Django 2.2.7 on 2019-11-12 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(null=True)),
                ('block_hash', models.CharField(blank=True, max_length=150)),
                ('block_data_hash', models.CharField(blank=True, max_length=150)),
                ('prev_block_hash', models.CharField(blank=True, max_length=150)),
                ('difficulty', models.SmallIntegerField(null=True)),
                ('transactions', models.CharField(blank=True, max_length=10000)),
                ('mined_by', models.CharField(blank=True, max_length=150)),
                ('nonce', models.IntegerField(null=True)),
                ('date_created', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenesisBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0, null=True)),
                ('difficulty', models.SmallIntegerField(default=0)),
                ('mined_by', models.CharField(default='000000000000000000000000000', max_length=150)),
                ('nonce', models.IntegerField(default=0)),
                ('block_data_hash', models.CharField(blank=True, max_length=150)),
                ('date_created', models.DateTimeField(null=True)),
                ('block_hash', models.CharField(blank=True, max_length=150)),
            ],
        ),
    ]
