# Generated by Django 2.2.7 on 2020-01-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0002_blockcandidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genesisblock',
            name='mined_by',
            field=models.CharField(default='0000000000000000000000000000', max_length=150),
        ),
    ]
