# Generated by Django 2.2.7 on 2019-11-12 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=150)),
                ('private_key', models.CharField(blank=True, max_length=150)),
                ('public_key', models.CharField(blank=True, max_length=150)),
                ('default_fee', models.IntegerField(blank=True, null=True)),
                ('balance', models.BigIntegerField(default=0, null=True)),
            ],
        ),
    ]
