# Generated by Django 2.2.7 on 2019-11-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='private_key',
            field=models.BinaryField(blank=True, max_length=150),
        ),
    ]
