# Generated by Django 2.2.7 on 2019-11-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(blank=True, max_length=150)),
                ('miner_address', models.CharField(blank=True, max_length=150)),
                ('peers', models.CharField(blank=True, max_length=5000)),
            ],
        ),
    ]
