# Generated by Django 2.2.7 on 2019-11-15 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='miner_address',
        ),
    ]
