# Generated by Django 2.2.7 on 2020-01-13 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0002_remove_node_miner_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(blank=True, max_length=150, unique=True)),
                ('node_url', models.CharField(blank=True, max_length=150)),
                ('related_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='node.Node')),
            ],
        ),
    ]
